# Generated by Django 2.1 on 2018-11-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='reponses_assert',
            new_name='responses_assert',
        ),
    ]
