# Generated by Django 2.1 on 2018-11-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0002_auto_20181113_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='responses_assert',
            new_name='resp_assert',
        ),
    ]
