# Generated by Django 2.1 on 2018-11-09 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['-create_time']},
        ),
    ]
